name = "Configuration for autogenerating tutorials from notebooks"

# List of tutorials
# NOTE: if sidebar <label> is omitted, it is set to <title>,
# and if <path> is omitted it is set to "<id>.ipynb"
[[tutorial]]
id = "learn_bivariate_normal"
title = "Your First Flow"

[[tutorial]]
id = "univariate_bijectors"
title = "Univariate Bijectors"

[[tutorial]]
id = "multivariate_bijectors"
title = "Multivariate Bijectors"

[[tutorial]]
id = "transport_score_climbing"
title = "Transport Score Climbing"

# Table of contents
[[section]]
title = "Getting Started"
ids = ["learn_bivariate_normal"]

[[section]]
title = "Background"
ids = ["univariate_bijectors", "multivariate_bijectors"]

[[section]]
title = "Bayesian Inference"
ids = ["transport_score_mapping"]

# NOTE: You can create an arbitrarily deep hierarchy
# using sections under sections ad infinitum
#[[section.section]]
#title = "Variation Inference"
#ids = ["flexible_vi", "structured_vi", "robust_vi"]
