name = "Configuration for autogenerating tutorials from notebooks"

[settings]
# This can be a list of strings if you want to document more than one module
search = ["flowtorch"]
github = "https://github.com/facebookincubator/flowtorch/blob/main/"

[paths]
# Paths are all relative to the *first* search module
sidebar = "../website"
sidebar_filename = "tutorials.sidebar.js"

# TODO: Base path for Docusaurus 2 content
markdown = "../website/docs/tutorials"

# TODO: regular expression for sections that are visible initially: unfurled = "..."

# List of tutorials
# NOTE: if sidebar <label> is omitted, it is set to <title>,
# and if <path> is omitted it is set to "<id>.ipynb"
[[tutorial]]
id = "learn_bivariate_normal"
title = "Your First Flow"

[[tutorial]]
id = "univariate_bijectors"
title = "Univariate Bijectors"

[[tutorial]]
id = "multivariate_bijectors"
title = "Multivariate Bijectors"

[[tutorial]]
id = "transport_score_climbing"
title = "Transport Score Climbing"

# Table of contents
[[section]]
title = "Getting Started"
ids = ["learn_bivariate_normal"]

[[section]]
title = "Background"
ids = ["univariate_bijectors", "multivariate_bijectors"]

[[section]]
title = "Bayesian Inference"
ids = ["transport_score_mapping"]

# NOTE: You can create an arbitrarily deep hierarchy
# using sections under sections ad infinitum
#[[section.section]]
#title = "Variation Inference"
#ids = ["flexible_vi", "structured_vi", "robust_vi"]
