name: Deploy On Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # TODO: swap this in after verifying
  # release:
  #   types: [created]

jobs:
  tests-and-coverage-pip:
    name: Tests and coverage (pip, Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (auto-install dependencies)
      run: |
        pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest --cov=tests --cov-report=xml -W ignore::DeprecationWarning tests/
    - name: Upload coverage to Codecov
      if: ${{ runner.os == 'Linux' && matrix.python-version == 3.7 }}
      uses: codecov/codecov-action@v1
      with:
        token: 9667eb01-c300-4166-b8ba-605deb2682e4
        files: coverage.xml
        directory: ./
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.txt
        verbose: true

  release-pypi:
    name: Release to pypi.org
    runs-on: ubuntu-latest
    needs: tests-and-coverage-pip
    # TODO: remove this guard after verifying on test pypi
    if: github.event_name == 'push' && github.repository == 'facebookincubator/flowtorch'
    strategy:
      fail-fast: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install packaging dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
    - name: Build source distribution
      run: python setup.py sdist bdist_wheel
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        verbose: true
        user: __token__
        # TODO: swap this in after verifying
        # password: ${{ secrets.PYPI_PASSWORD }}
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
