# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black isort pytest mypy
        pip install numpy
        pip install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install -e .[dev]
    - name: Check formatting with black
      run: |
        black --check flowtorch tests
    - name: Check imports with isort
      run: |
        isort --check flowtorch tests
    - name: Lint with flake8
      run: |
        flake8 flowtorch tests --count --show-source --statistics
    - name: Check types with mypy
      run: |
        mypy flowtorch
    - name: Test with pytest
      run: |
        pytest --cov=tests --cov-report=xml -W ignore::DeprecationWarning tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 6db8e3c4-f052-4124-abda-13e0f0fe346a
        files: coverage.xml
        directory: ./
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.txt
        verbose: true
    - name: Sphinx Build
      run: |
        cd docs
        sphinx-apidoc -o source ../flowtorch/
        make html
